### ISSUE TITLE
Unclear how to use JerseyGuiceServletContextListener.

### ISSUE THREAD

**Issue by dlazerka** [Squarespace/jersey2-guice#11]
Hi Roger, nice tool!
By reading User Guide it's still a mystery for me on how to use JerseyGuiceServletContextListener. E.g. where to put Jersey config, or where to put pre-jersey filters.

**Comment by wfuertes** [comment]
I have doubt about GuiceContainer, for example in jersey 1.x we have used:

public class GuiceServletConfig extends GuiceServletContextListener {
 
         @Override
         protected Injector getInjector() {
             return Guice.createInjector(new JerseyServletModule() {
 
                 @Override
                 protected void configureServlets() {
                     bind(GuiceResource.class);

                     Map<String, String> params = new HashMap<String, String>();
                     params.put(PackagesResourceConfig.PROPERTY_PACKAGES, "unbound");
                     serve("/*").with(GuiceContainer.class, params);
                 }
             });
         }
     }

And about GuiceContainer, do you have any example to clarify that?

**Comment by GuiSim** [comment]
Same question here.
A more elaborate "examples" section would be very helpful.

**Comment by Bathlamos** [comment]
Same question here too.
