### ISSUE TITLE
base path

### ISSUE THREAD

**Issue by natros** [Squarespace/jersey2-guice#15]
I have my listener

```java
public class GuiceListener extends JerseyGuiceServletContextListener {
    @Override
    protected List<? extends Module> modules() {
        return newArrayList(new DashboardModule());
    }
}
```

my module
```java
public class DashboardModule extends ServletModule {
    @Override
    protected void configureServlets() {
        bind(HelloResource.class);
    }
}
```

my resuorce
```java
@Path("/hello")
public class HelloResource {
    @GET
    @Produces("text/plain")
    public String getMessage() {
        return "hello world";
    }
}
``` 

and my web.xml
```xml
<filter>
        <filter-name>GuiceFilter</filter-name>
        <filter-class>com.google.inject.servlet.GuiceFilter</filter-class>
    </filter>
    <filter-mapping>
        <filter-name>GuiceFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>

    <listener>
        <listener-class>pt.ipb.sa.dashboard.guice.GuiceListener</listener-class>
    </listener>
```

what do I tell jersey that should use /rest/* as my base path

with the old jersey-guice and would have done the following
```java
serve("/rest/*").with(GuiceContainer.class, params);
```

what should I do with jersey2-guice?

**Comment by set321go** [comment]
Not sure if this is the cause of your problems 

    public static Injector newInjector(ServiceLocator locator, Stage stage, Iterable<? extends Module> modules) {
    
        List<Module> copy = new ArrayList<>();
        for (Module module : modules) {
           copy.add(module);
       }
    
       // It seems people are forgetting to install the ServletModule.
        copy.add(new ServletModule());
        copy.add(new BootstrapModule(locator));
    
        Injector injector = createInjector(stage, copy);
    
        link(locator, injector);
    
        return injector;
     }

I'm doing some research to decide if this will work for me and i'm assuming the fact that the bootstrap registers an additional servlet module is probably going to cause me problems.

I have a few modules configured:
Servlet
JPA
Shiro
MyApplication

what about checking for that module before adding it?
        
        boolean hasServletModule = false;
        for (Module module : modules) {
           if (module.getClass().isAssignableFrom(ServletModule.class)) {
                hasServletModule = true;
           }
           copy.add(module);
       }

       if (!hasServletModule) { copy.add(new ServletModule()); }
