### ISSUE TITLE
AOP requires registration in two places

### ISSUE THREAD

**Issue by stickfigure** [Squarespace/jersey2-guice#17]
This may be "working as advertised", but it seems a bit weird.

Resource classes need to be registered with Jersey (through the ResourceConfig, either individually or via `packages()`). If they are registered with Guice only, they don't show up as endpoints (ie, they are 404). However, they don't need to be registered/bound separately with Guice to receive Guice injection.

However, in order to receive AOP, resource classes must also be registered/bound with Guice.

Is there a way to make registration necessary only in one place, either with Guice or with Jersey? It's almost there, it just doesn't seem to work with AOP. FWIW I don't care if it's Guice-side or Jersey-side that requires registration/binding.

**Comment by vshankri** [comment]
I guess i am get 404 as I have not registered explicitly registered services with Jersey through ResourceConfig

I get 404 for all REST endpoints

I think With Jersey 1.x "com.sun.jersey.guice.spi.container.servlet.GuiceContainer" did the registering part. Do we have anything equivalent of this?

**Comment by rkapsi** [comment]
Is this still an issue?

**Comment by misaunde** [comment]
Any solutions to this? I'm having the same issue.

**Comment by misaunde** [comment]
Ahh, this fixed it for me:
https://github.com/Squarespace/jersey2-guice/wiki#aop-with-guice

Force HK2 to use Guice by using explicit bindings for those classes, and also remember to change the @Inject annotation on the constructors in those classes to use com.google.inject.Inject.
