### ISSUE TITLE
JerseyGuiceServletContextListener uses constructor to Initialize injector

### ISSUE THREAD

**Issue by set321go** [Squarespace/jersey2-guice#19]
This breaks registration of modules that require the ServiceContext like ApacheShiro. 

GuiceServletContextListener creates the injector in contextInitialized.

As well as breaking things that are possible with the guice servlet module it is bad practice to reference abstract/interface methods from your constructor http://stackoverflow.com/questions/3404301/whats-wrong-with-overridable-method-calls-in-constructors

**Comment by rkapsi** [comment]
Have you taken a closer look into why it's using the constructor? There is an inherit chicken-egg problem in regards to Jersey's own DI framework (HK2) and Guice. To make things work it's necessary swap out HK2's own ServiceLoator/ServiceLocatorGenerator (static singleton) with a different instance that has Guice support. This needs to happen as early as possible and ideally before anything gets their hands on the ServiceLoator/ServiceLocatorGenerator.

Doing it in ServletContextListener#contextInitialized() is potentially too late. Feel free to experiment with it though. It may work, I really don't know.
