### ISSUE TITLE
How to get custom @Context injections?

### ISSUE THREAD

**Issue by mumrah** [Squarespace/jersey2-guice#24]
Migrating a Jersey 1.x app, we have some classes that are injected via `@Context`. Previously, this was done like:

```java
@javax.ws.rs.ext.Provider
public class MyCustomThingProvider extends AbstractHttpContextInjectable<MyCustomThing>
    implements InjectableProvider<Context, Type> {
  ...
}
```

Based on the Jersey 2.x manual, the way to do this is with an HK2 Factory, like:

```java
public class MyCustomThingFactory implements Factory<MyCustomThing> {

  private final UriInfo uriInfo;

  @Inject
  protected MyCustomThingFactory(UriInfo uriInfo) {
    this.uriInfo = uriInfo;
  }

  ...
}
```

Before, I could pull out the things I needed from the request when implementing `AbstractHttpContextInjectable#getValue(HttpContext)`. Now, it looks like the preferred method is to inject things to the factory itself (things like HttpServletRequest, UriInfo, etc).

This is all fine, and I actually have it working, but my question is: how can I avoid having to do some HK2 binding in my application setup? The only way I could get this working is to add an HK2 binder:

```java
jerseyConfig.register(new AbstractBinder() {
      @Override
      protected void configure() {
        bindFactory(MyCustomThingFactory.class).to(MyCustomThing.class);
      }
    });
```

Any ideas?

**Comment by rkapsi** [comment]
Hello,

since you're using `jersey2-guice` I'd actually recommend to use Guice for this. The trick to force HK2 into using Guice is to add explicit bindings for everything that you want to be under Guice's control.

Does this help?

```
public class MyCustomThingModule extends AbstractModule {
  @Override
  protected void configure() {
    bind(MyCustomThing.class);
  }
}

public class MyCustomThing {
  @Inject
  public MyCustomThing(UriInfo uriInfo) {

  }
}
```
