### ISSUE TITLE
0.8 relies on guice 4.0-SNAPSHOT

### ISSUE THREAD

**Issue by facboy** [Squarespace/jersey2-guice#26]
is this intentional?  it seems a bit odd to release it to Maven central with a dependency on a snapshot version.

**Comment by rkapsi** [comment]
Yes it's intentional. We use HEAD in production (like Google). If it's a problem I can make it depend on Beta5.
 
https://groups.google.com/d/msg/google-guice/mlgZgKiJyU8/VJnyDCfc9FYJ

**Comment by facboy** [comment]
Well I can handle that myself with dependency management, but personally for a released version I think it would better to have it depend on a version that is stable and that is also available on Central, especially as it sounds like it doesn't particularly require HEAD.

**Comment by rkapsi** [comment]
Fair enough. Released 0.9 that depends on 4.0-beta5.

**Comment by natros** [comment]
4.0 has been released

**Comment by facboy** [comment]
Thanks
