### ISSUE TITLE
Error injecting constructor, java.lang.IllegalStateException

### ISSUE THREAD

**Issue by ruddy32** [Squarespace/jersey2-guice#31]
While deploying an application that includes wars and ejb, glassfish server show following messages:
> GRAVE: Exception while loading the app : java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: com.google.inject.CreationException: Unable to create injector, see the following errors:
> 1) Error injecting constructor, java.lang.IllegalStateException: name=com.pa.APIShiroWebModule
>   at com.pa.HK2Linker.<init>(HK2Linker.java:23)
>   at com.pa.APIJerseyModule.configureServlets(APIJerseyModule.java:49)
>   while locating com.pa.HK2Linker

Source code:
> ...
> 		final ServiceLocator locator = BootstrapUtils.newServiceLocator();
> 		install(new BootstrapModule(locator));
> 		bind(HK2Linker.class).asEagerSingleton();
> ...
> 
> public class HK2Linker {
> 	@Inject
> 	public HK2Linker(Injector injector, ServiceLocator locator) {
> 		BootstrapUtils.link(locator, injector);
> 		BootstrapUtils.install(locator);
> 	}
> }
APIShiroWebModule is a simple module herited from ShiroWebModule.
What's goiing wrong?

**Comment by rkapsi** [comment]
Hello,

the Shiro project has come up a few times. We're not using it and it's hence difficult to debug it. The snippet is a bit short to tell what's wrong but appears you're trying to link+install via `@Inject` which will not work.

**Comment by ruddy32** [comment]
It works fine in a standalone WAR project.

I fix the @Inject annotation that was the one of javax, replaced by the one of Guice. The same trouble happen.
