### ISSUE TITLE
java.lang.IllegalStateException: ServiceLocatorImpl(GuiceServiceLocator-9,8,1066656936) has been shut down

### ISSUE THREAD

**Issue by facboy** [Squarespace/jersey2-guice#32]
I'm getting these since upgrading to jersey 2.21...in the constructor of AbstractRuntimeDelegate jersey now shuts down the ServiceLocator that it is given, so when Guice tries to access it it gets this error.

**Comment by scho** [comment]
Any news on this?

**Comment by loicAG** [comment]
I'm running into the same issue on dropwizard 0.8.2

**Comment by scho** [comment]
We do not have this issue with dropwizard 0.8.2 and 0.8.3. Maybe you need use the BootstrapUtils in your tests as advised in dropwizard-guice?

**Comment by loicAG** [comment]
I'm confused as to why I'm running into the issue actually, since dropwizard 0.8.2 uses jersey 2.19, and the presumed culprit (https://github.com/jersey/jersey/commit/ad54f0033c73144f1ad23706583714a3fe84bee7) was introduced in jersey 2.20... I'll try modifying the test as you suggest and will post the result here

**Comment by loicAG** [comment]
No dice, just ignoring that test for now :(

**Comment by magnus-gustafsson** [comment]
I got the same issue when upgrading from jersey-common 2.17 to 2.22.

**Comment by rvs-fluid-it** [comment]
I created a fork with a workaround for the issue:
https://github.com/rvs-fluid-it/jersey2-guice
But I'm not sure if the workaround does not have any side effects (resources leaking ...)
Hence I currently do not have enough confidence in the solution to prepare a pull request.
But if you want to take it for a test drive, please feel free :-).

**Comment by jhaber** [comment]
I used a hacky [workaround](https://github.com/HubSpot/dropwizard-guice/commit/3355c9a08b31560176409f8e7501a48e79229755) which was to decorate the `ServiceLocator` before passing it to jersey2-guice and override the `shutdown` method to do nothing

**Comment by rkapsi** [comment]
Hello,

I've just pushed a new build to Maven Central. There are some breaking API changes but this problem should be fixed. Please take a look at the updated documentation which should be straight forward if you're running your code from a `main()` method (e.g. Dropwizard).

**Comment by cowwoc** [comment]
If you want to see this fixed in Jersey proper, please put pressure on https://java.net/jira/browse/JERSEY-2627.

**Comment by cowwoc** [comment]
If you want to see this fixed in Jersey proper, please put pressure on https://java.net/jira/browse/JERSEY-2627.
